In [ ]:
%pip install sklearn

In [3]:
from datetime import datetime
import os
from sklearn import *
import pandas as pd

In [5]:
dataset=[
  [0,0,0],
  [0,1,1],
  [1,0,1],
  [1,1,1]
]
columns=["a","b","a_or_b"]
ordf = pd.DataFrame(dataset,columns=columns)

In [6]:
ordf

a  b  a_or_b
0  0  0       0
1  0  1       1
2  1  0       1
3  1  1       1

In [7]:
ordf.to_csv('./ordf.csv')

In [9]:
%ls

ordf.csv  python.ipynb


In [3]:
lendo_o_ativo=pd.read_csv("ordf.csv")

In [11]:
lendo_o_ativo

Unnamed: 0  a  b  a_or_b
0           0  0  0       0
1           1  0  1       1
2           2  1  0       1
3           3  1  1       1

In [12]:
lendo_o_ativo.values

array([[0, 0, 0, 0],
       [1, 0, 1, 1],
       [2, 1, 0, 1],
       [3, 1, 1, 1]])

In [13]:
lendo_o_ativo.columns

Index(['Unnamed: 0', 'a', 'b', 'a_or_b'], dtype='object')

In [4]:
lendo_o_ativo.sample(4)

Unnamed: 0  a  b  a_or_b
0           0  0  0       0
3           3  1  1       1
1           1  0  1       1
2           2  1  0       1

In [17]:
json_array=[ {'a':1,'b':2}, {'a':3,'b':4}, {'a':5,'b':6} ] 
df = pd.DataFrame(json_array)
df.to_json('./df.json', orient='records')

In [5]:
df

a  b
0  1  2
1  3  4
2  5  6

In [22]:
import json

json_array='[{"a":1,"b":2},{"a":3,"b":4},{"a":5,"b":6}]'
df = pd.DataFrame(json.loads(json_array) )
df

a  b
0  1  2
1  3  4
2  5  6

In [23]:
from sklearn.datasets import load_iris

In [143]:
data = load_iris()

In [150]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [26]:
iris_df=pd.DataFrame(data.data,columns=data.feature_names)
iris_df['encoded_target']=data.target

In [27]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[150 rows x 5 columns]

In [31]:
iris_df.iloc[0,0]=None
iris_df.iloc[0,1]=None
iris_df.iloc[0,2]=None
iris_df.iloc[1,0]=None
iris_df.iloc[4,3]=None
iris_df.iloc[149,2]=None
iris_df.iloc[3,3]=-99999999999
iris_df.iloc[149,2]="cwevawevberbqb"

In [37]:
iris_df.to_csv('./iris_df.csv')

In [35]:
iris_df.isna()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 True              True               True             False   
1                 True             False              False             False   
2                False             False              False             False   
3                False             False              False             False   
4                False             False              False              True   
..                 ...               ...                ...               ...   
145              False             False              False             False   
146              False             False              False             False   
147              False             False              False             False   
148              False             False              False             False   
149              False             False              False             False   

     encoded_target  
0             False  
1             False  
2             False  
3             False  
4             False  
..              ...  
145           False  
146           False  
147           False  
148           False  
149           False  

[150 rows x 5 columns]

In [40]:
iris_df[iris_df.isna().any(axis=1)]

sepal length (cm)  sepal width (cm) petal length (cm)  petal width (cm)  \
0                NaN               NaN               NaN               0.2   
1                NaN               3.0               1.4               0.2   
4                5.0               3.6               1.4               NaN   

   encoded_target  
0               0  
1               0  
4               0

In [41]:
iris_df_rem=iris_df.dropna()

In [42]:
iris_df_rem

sepal length (cm)  sepal width (cm) petal length (cm)  petal width (cm)  \
2                  4.7               3.2               1.3      2.000000e-01   
3                  4.6               3.1               1.5     -1.000000e+11   
5                  5.4               3.9               1.7      4.000000e-01   
6                  4.6               3.4               1.4      3.000000e-01   
7                  5.0               3.4               1.5      2.000000e-01   
..                 ...               ...               ...               ...   
145                6.7               3.0               5.2      2.300000e+00   
146                6.3               2.5               5.0      1.900000e+00   
147                6.5               3.0               5.2      2.000000e+00   
148                6.2               3.4               5.4      2.300000e+00   
149                5.9               3.0    cwevawevberbqb      1.800000e+00   

     encoded_target  
2                 0  
3                 0  
5                 0  
6                 0  
7                 0  
..              ...  
145               2  
146               2  
147               2  
148               2  
149               2  

[147 rows x 5 columns]

In [ ]:
iris_df_mean=iris_df.fillna(iris_df.mean())
iris_df_zero=iris_df.fillna(0)
iris_df_impossible=iris_df.fillna(-999)

In [43]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  148 non-null    float64
 1   sepal width (cm)   149 non-null    float64
 2   petal length (cm)  149 non-null    object 
 3   petal width (cm)   149 non-null    float64
 4   encoded_target     150 non-null    int64  
dtypes: float64(3), int64(1), object(1)
memory usage: 6.0+ KB


In [44]:
iris_df['petal length (cm)'].unique()

array([nan, 1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1.0, 1.9, 4.7, 4.5, 4.9,
       4.0, 4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5.0, 3.8,
       3.7, 5.1, 3.0, 6.0, 5.9, 5.6, 5.8, 6.6, 6.3, 6.1, 5.3, 5.5, 6.7,
       6.9, 5.7, 6.4, 5.4, 5.2, 'cwevawevberbqb'], dtype=object)

In [46]:
iris_df=iris_df[iris_df['petal length (cm)'] != 'cwevawevberbqb'].reset_index(drop=True)

In [47]:
iris_df

sepal length (cm)  sepal width (cm) petal length (cm)  petal width (cm)  \
0                  NaN               NaN               NaN      2.000000e-01   
1                  NaN               3.0               1.4      2.000000e-01   
2                  4.7               3.2               1.3      2.000000e-01   
3                  4.6               3.1               1.5     -1.000000e+11   
4                  5.0               3.6               1.4               NaN   
..                 ...               ...               ...               ...   
144                6.7               3.3               5.7      2.500000e+00   
145                6.7               3.0               5.2      2.300000e+00   
146                6.3               2.5               5.0      1.900000e+00   
147                6.5               3.0               5.2      2.000000e+00   
148                6.2               3.4               5.4      2.300000e+00   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
144               2  
145               2  
146               2  
147               2  
148               2  

[149 rows x 5 columns]

In [48]:
iris_df['petal length (cm)'].unique()


array([nan, 1.4, 1.3, 1.5, 1.7, 1.6, 1.1, 1.2, 1.0, 1.9, 4.7, 4.5, 4.9,
       4.0, 4.6, 3.3, 3.9, 3.5, 4.2, 3.6, 4.4, 4.1, 4.8, 4.3, 5.0, 3.8,
       3.7, 5.1, 3.0, 6.0, 5.9, 5.6, 5.8, 6.6, 6.3, 6.1, 5.3, 5.5, 6.7,
       6.9, 5.7, 6.4, 5.4, 5.2], dtype=object)

In [49]:
iris_df['petal width (cm)'].unique()

array([ 2.0e-01, -1.0e+11,      nan,  4.0e-01,  3.0e-01,  1.0e-01,
        5.0e-01,  6.0e-01,  1.4e+00,  1.5e+00,  1.3e+00,  1.6e+00,
        1.0e+00,  1.1e+00,  1.8e+00,  1.2e+00,  1.7e+00,  2.5e+00,
        1.9e+00,  2.1e+00,  2.2e+00,  2.0e+00,  2.4e+00,  2.3e+00])

In [53]:
t=iris_df['petal width (cm)'] != -1.0e+11
t

0      True
1      True
2      True
3      True
4      True
       ... 
144    True
145    True
146    True
147    True
148    True
Name: petal width (cm), Length: 149, dtype: bool

In [55]:
iris_df=iris_df[iris_df['petal width (cm)'] != -1.0e+11]

In [56]:
iris_df

sepal length (cm)  sepal width (cm) petal length (cm)  petal width (cm)  \
0                  NaN               NaN               NaN      2.000000e-01   
1                  NaN               3.0               1.4      2.000000e-01   
2                  4.7               3.2               1.3      2.000000e-01   
3                  4.6               3.1               1.5     -1.000000e+11   
4                  5.0               3.6               1.4               NaN   
..                 ...               ...               ...               ...   
144                6.7               3.3               5.7      2.500000e+00   
145                6.7               3.0               5.2      2.300000e+00   
146                6.3               2.5               5.0      1.900000e+00   
147                6.5               3.0               5.2      2.000000e+00   
148                6.2               3.4               5.4      2.300000e+00   

     encoded_target  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
144               2  
145               2  
146               2  
147               2  
148               2  

[149 rows x 5 columns]

In [57]:
import numpy as np
iris_df['artifical']=np.random.uniform(100,1000,iris_df.shape[0]).round(2)

In [58]:
iris_df

sepal length (cm)  sepal width (cm) petal length (cm)  petal width (cm)  \
0                  NaN               NaN               NaN      2.000000e-01   
1                  NaN               3.0               1.4      2.000000e-01   
2                  4.7               3.2               1.3      2.000000e-01   
3                  4.6               3.1               1.5     -1.000000e+11   
4                  5.0               3.6               1.4               NaN   
..                 ...               ...               ...               ...   
144                6.7               3.3               5.7      2.500000e+00   
145                6.7               3.0               5.2      2.300000e+00   
146                6.3               2.5               5.0      1.900000e+00   
147                6.5               3.0               5.2      2.000000e+00   
148                6.2               3.4               5.4      2.300000e+00   

     encoded_target  artifical  
0                 0     239.54  
1                 0     814.40  
2                 0     355.02  
3                 0     694.41  
4                 0     267.26  
..              ...        ...  
144               2     831.22  
145               2     103.82  
146               2     642.84  
147               2     190.08  
148               2     764.70  

[149 rows x 6 columns]

In [59]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

print(scaler.fit(iris_df))
novo_iris_df=scaler.transform(iris_df)
MinMaxScaler()

MinMaxScaler()


MinMaxScaler()

In [60]:
novo_iris_df=pd.DataFrame(novo_iris_df, columns=iris_df.columns).round(2)

In [61]:
novo_iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  NaN               NaN                NaN               1.0   
1                  NaN              0.42               0.07               1.0   
2                 0.11              0.50               0.05               1.0   
3                 0.08              0.46               0.08               0.0   
4                 0.19              0.67               0.07               NaN   
..                 ...               ...                ...               ...   
144               0.67              0.54               0.80               1.0   
145               0.67              0.42               0.71               1.0   
146               0.56              0.21               0.68               1.0   
147               0.61              0.42               0.71               1.0   
148               0.53              0.58               0.75               1.0   

     encoded_target  artifical  
0               0.0       0.15  
1               0.0       0.80  
2               0.0       0.28  
3               0.0       0.66  
4               0.0       0.18  
..              ...        ...  
144             1.0       0.81  
145             1.0       0.00  
146             1.0       0.60  
147             1.0       0.10  
148             1.0       0.74  

[149 rows x 6 columns]

In [62]:
novo_iris_df['encoded_target'].unique()

array([0. , 0.5, 1. ])

In [63]:
novo_iris_df['petal width (cm)'].unique()


array([ 1.,  0., nan])

Regularização de dados

In [64]:
novo_iris_df['artifical'].unique()

array([0.15, 0.8 , 0.28, 0.66, 0.18, 0.64, 0.7 , 0.95, 0.11, 0.77, 0.52,
       0.1 , 0.14, 0.87, 0.24, 0.41, 0.54, 0.12, 0.32, 0.4 , 0.62, 0.94,
       0.43, 0.63, 0.82, 0.49, 0.16, 0.99, 0.47, 0.67, 0.42, 0.51, 0.22,
       0.38, 0.13, 0.35, 0.81, 0.88, 0.5 , 0.23, 0.98, 1.  , 0.27, 0.6 ,
       0.74, 0.79, 0.97, 0.57, 0.56, 0.45, 0.48, 0.09, 0.07, 0.06, 0.17,
       0.86, 0.93, 0.39, 0.89, 0.3 , 0.61, 0.03, 0.91, 0.04, 0.92, 0.26,
       0.  , 0.34, 0.9 , 0.44, 0.02, 0.76, 0.83, 0.25, 0.21, 0.71, 0.96,
       0.68, 0.05])

In [65]:
novo_iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  NaN               NaN                NaN               1.0   
1                  NaN              0.42               0.07               1.0   
2                 0.11              0.50               0.05               1.0   
3                 0.08              0.46               0.08               0.0   
4                 0.19              0.67               0.07               NaN   
..                 ...               ...                ...               ...   
144               0.67              0.54               0.80               1.0   
145               0.67              0.42               0.71               1.0   
146               0.56              0.21               0.68               1.0   
147               0.61              0.42               0.71               1.0   
148               0.53              0.58               0.75               1.0   

     encoded_target  artifical  
0               0.0       0.15  
1               0.0       0.80  
2               0.0       0.28  
3               0.0       0.66  
4               0.0       0.18  
..              ...        ...  
144             1.0       0.81  
145             1.0       0.00  
146             1.0       0.60  
147             1.0       0.10  
148             1.0       0.74  

[149 rows x 6 columns]

In [66]:
novo_iris_df.columns=[c.replace("(cm)","").rstrip().replace(" ","_") for c in novo_iris_df.columns]

In [67]:
novo_iris_df

sepal_length  sepal_width  petal_length  petal_width  encoded_target  \
0             NaN          NaN           NaN          1.0             0.0   
1             NaN         0.42          0.07          1.0             0.0   
2            0.11         0.50          0.05          1.0             0.0   
3            0.08         0.46          0.08          0.0             0.0   
4            0.19         0.67          0.07          NaN             0.0   
..            ...          ...           ...          ...             ...   
144          0.67         0.54          0.80          1.0             1.0   
145          0.67         0.42          0.71          1.0             1.0   
146          0.56         0.21          0.68          1.0             1.0   
147          0.61         0.42          0.71          1.0             1.0   
148          0.53         0.58          0.75          1.0             1.0   

     artifical  
0         0.15  
1         0.80  
2         0.28  
3         0.66  
4         0.18  
..         ...  
144       0.81  
145       0.00  
146       0.60  
147       0.10  
148       0.74  

[149 rows x 6 columns]

In [68]:
novo_iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sepal_length    147 non-null    float64
 1   sepal_width     148 non-null    float64
 2   petal_length    148 non-null    float64
 3   petal_width     148 non-null    float64
 4   encoded_target  149 non-null    float64
 5   artifical       149 non-null    float64
dtypes: float64(6)
memory usage: 7.1 KB


In [69]:
novo_iris_df.describe()

sepal_length  sepal_width  petal_length  petal_width  encoded_target  \
count    147.000000   148.000000    148.000000   148.000000      149.000000   
mean       0.431701     0.439595      0.467973     0.993243        0.496644   
std        0.230875     0.182081      0.299217     0.082199        0.408923   
min        0.000000     0.000000      0.000000     0.000000        0.000000   
25%        0.220000     0.330000      0.100000     1.000000        0.000000   
50%        0.420000     0.420000      0.570000     1.000000        0.500000   
75%        0.580000     0.540000      0.690000     1.000000        1.000000   
max        1.000000     1.000000      1.000000     1.000000        1.000000   

        artifical  
count  149.000000  
mean     0.528792  
std      0.305919  
min      0.000000  
25%      0.240000  
50%      0.520000  
75%      0.810000  
max      1.000000

#projeção

In [70]:
novo_iris_df.loc[0]

sepal_length       NaN
sepal_width        NaN
petal_length       NaN
petal_width       1.00
encoded_target    0.00
artifical         0.15
Name: 0, dtype: float64

In [75]:
novo_iris_df.describe().loc['mean']

sepal_length      0.431701
sepal_width       0.439595
petal_length      0.467973
petal_width       0.993243
encoded_target    0.496644
artifical         0.528792
Name: mean, dtype: float64

In [76]:
novo_iris_df.iloc[1]

sepal_length       NaN
sepal_width       0.42
petal_length      0.07
petal_width       1.00
encoded_target    0.00
artifical         0.80
Name: 1, dtype: float64

In [93]:
novo_iris_df.iloc[0:2,0:2]

sepal_length  sepal_width
0           NaN          NaN
1           NaN         0.42

In [97]:
novo_iris_df.iloc[0:2,[2]]

petal_length
0           NaN
1          0.07

#Deleção

In [98]:
novo_iris_df.drop([0])

sepal_length  sepal_width  petal_length  petal_width  encoded_target  \
1             NaN         0.42          0.07          1.0             0.0   
2            0.11         0.50          0.05          1.0             0.0   
3            0.08         0.46          0.08          0.0             0.0   
4            0.19         0.67          0.07          NaN             0.0   
5            0.31         0.79          0.12          1.0             0.0   
..            ...          ...           ...          ...             ...   
144          0.67         0.54          0.80          1.0             1.0   
145          0.67         0.42          0.71          1.0             1.0   
146          0.56         0.21          0.68          1.0             1.0   
147          0.61         0.42          0.71          1.0             1.0   
148          0.53         0.58          0.75          1.0             1.0   

     artifical  
1         0.80  
2         0.28  
3         0.66  
4         0.18  
5         0.64  
..         ...  
144       0.81  
145       0.00  
146       0.60  
147       0.10  
148       0.74  

[148 rows x 6 columns]

In [107]:
novo_iris_df.query("sepal_length >= 1").index

Int64Index([131], dtype='int64')

In [120]:
novo_iris_df.drop(novo_iris_df.query("sepal_length >= 1").index).reset_index()

index  sepal_length  sepal_width  petal_length  petal_width  \
0        0           NaN          NaN           NaN          1.0   
1        1           NaN         0.42          0.07          1.0   
2        2          0.11         0.50          0.05          1.0   
3        3          0.08         0.46          0.08          0.0   
4        4          0.19         0.67          0.07          NaN   
..     ...           ...          ...           ...          ...   
143    144          0.67         0.54          0.80          1.0   
144    145          0.67         0.42          0.71          1.0   
145    146          0.56         0.21          0.68          1.0   
146    147          0.61         0.42          0.71          1.0   
147    148          0.53         0.58          0.75          1.0   

     encoded_target  artifical  
0               0.0       0.15  
1               0.0       0.80  
2               0.0       0.28  
3               0.0       0.66  
4               0.0       0.18  
..              ...        ...  
143             1.0       0.81  
144             1.0       0.00  
145             1.0       0.60  
146             1.0       0.10  
147             1.0       0.74  

[148 rows x 7 columns]

#junção

In [122]:
s1=pd.Series(['a','b'])
s2=pd.Series(['c','d'])

In [125]:
pd.concat([s1,s2],axis=1)

0  1
0  a  c
1  b  d

#União

In [126]:
pd.concat([s1,s2],axis=0)


0    a
1    b
0    c
1    d
dtype: object

In [128]:
df1=pd.DataFrame({'1key':['foo','bar','baz','foo'],
                  'value':[1,2,3,5]
                  })

df2=pd.DataFrame({'rkey':['foo','bar','baz','foo'],
                  'value':[5,6,7,8]
                  })

df1.merge(df2,left_on='1key',right_on='rkey',suffixes=("_left","_right"))

1key  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  foo           5  foo            5
3  foo           5  foo            8
4  bar           2  bar            6
5  baz           3  baz            7

In [134]:
df1=pd.DataFrame({'1key':['foo','bar','baz','foo'],
                  'value':[1,2,3,5]
                  })

df2=pd.DataFrame({'rkey':['foo','bar','baz'],
                  'value':[5,6,7]
                  })

df1.join(df2,lsuffix='_caller',rsuffix='other')

1key  value_caller rkey  valueother
0  foo             1  foo         5.0
1  bar             2  bar         6.0
2  baz             3  baz         7.0
3  foo             5  NaN         NaN

In [136]:
df1.join(df2,lsuffix='_caller',rsuffix='other', how='right')

1key  value_caller rkey  valueother
0  foo             1  foo           5
1  bar             2  bar           6
2  baz             3  baz           7

#Agregações - groupby

In [137]:
novo_iris_df.groupby(by=['encoded_target']).count()

sepal_length  sepal_width  petal_length  petal_width  \
encoded_target                                                         
0.0                       48           49            49           49   
0.5                       50           50            50           50   
1.0                       49           49            49           49   

                artifical  
encoded_target             
0.0                    50  
0.5                    50  
1.0                    49

In [142]:
novo_iris_df.groupby(by=['encoded_target']).mean().reset_index()


encoded_target  sepal_length  sepal_width  petal_length  petal_width  \
0             0.0      0.195833     0.593878      0.077347     0.979592   
1             0.5      0.454200     0.321400      0.552400     1.000000   
2             1.0      0.639796     0.405918      0.772449     1.000000   

   artifical  
0   0.492800  
1   0.546400  
2   0.547551

#Função Apply

In [151]:
target_names=data.target_names
def mapear_especie(x):
  return target_names[x]


In [153]:
novo_iris_df['especie']=iris_df['encoded_target'].apply(lambda x:mapear_especie(x))

In [154]:
novo_iris_df

sepal_length  sepal_width  petal_length  petal_width  encoded_target  \
0             NaN          NaN           NaN          1.0             0.0   
1             NaN         0.42          0.07          1.0             0.0   
2            0.11         0.50          0.05          1.0             0.0   
3            0.08         0.46          0.08          0.0             0.0   
4            0.19         0.67          0.07          NaN             0.0   
..            ...          ...           ...          ...             ...   
144          0.67         0.54          0.80          1.0             1.0   
145          0.67         0.42          0.71          1.0             1.0   
146          0.56         0.21          0.68          1.0             1.0   
147          0.61         0.42          0.71          1.0             1.0   
148          0.53         0.58          0.75          1.0             1.0   

     artifical    especie  
0         0.15     setosa  
1         0.80     setosa  
2         0.28     setosa  
3         0.66     setosa  
4         0.18     setosa  
..         ...        ...  
144       0.81  virginica  
145       0.00  virginica  
146       0.60  virginica  
147       0.10  virginica  
148       0.74  virginica  

[149 rows x 7 columns]